### ISSUE TITLE
cargo build failed

### ISSUE THREAD

**Issue by qixuxiang** [daogangtang/sapp-rs#1]
ubuntu X64 and centos X64 on win10 vmware
rustc 1.10.0-nightly (8492b6aa4 2016-05-14)
error:failed to run custom build command for `openssl-sys-extras v0.7.11`
details : Process didn't exit successfully: `/usr/gitplace/sapper/examples/basic/target/debug/build/openssl-sys-extras-581243db77f2742c/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("0")
PROFILE = Some("debug")
TARGET = Some("x86_64-unknown-linux-gnu")
debug=true opt-level=0
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = None
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-g" "-m64" "-fPIC" "-o" "/usr/gitplace/sapper/examples/basic/target/debug/build/openssl-sys-extras-581243db77f2742c/out/src/openssl_shim.o" "-c" "src/openssl_shim.c"
ExitStatus(ExitStatus(256))

command did not execute successfully, got: exit code: 1

--- stderr
src/openssl_shim.c:1:26: fatal error: openssl/hmac.h: No such file or directory
 #include <openssl/hmac.h>
                          ^
compilation terminated.
thread '<main>' panicked at 'explicit panic', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.28/src/lib.rs:840
note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by miketang84** [comment]
> --- stderr
> src/openssl_shim.c:1:26: fatal error: openssl/hmac.h: No such file or directory
> #include
> ^
> compilation terminated.
> thread '

I met it too, but after I cargo update, it resolved. And did you install libssl-dev on ubuntu?

**Comment by qixuxiang** [comment]
Hi,Mike,I managed to run it in my ubuntu ,thanks!

**Comment by miketang84** [comment]
nice
