### ISSUE TITLE
Add to crates.io

### ISSUE THREAD

**Issue by dumindu** [daogangtang/sapp-rs#10]
Please add this to crates.io. 
Also kindly refer https://github.com/bashyHQ/arewewebyet/issues/45
Thanks

**Comment by miketang84** [comment]
hi, I am waiting the tokio branck of hyper to refactory.  so, I think its' better to wait it now.

thx.

**Comment by dumindu** [comment]
Agree. Thanks :)

**Comment by dvic** [comment]
I believe async in hyper is now merged and published? In that case: any chance of publishing it now :)?

**Comment by miketang84** [comment]
Ok, I'll do it recently. Thx.

**Comment by miketang84** [comment]
All done.
