### ISSUE TITLE
Use diesel instead of sporm?

### ISSUE THREAD

**Issue by Anachron** [daogangtang/sapp-rs#2]
To Quote: 

> [Diesel](http://diesel.rs/) is the most productive way to interact with databases in Rust because of its safe and composable abstractions over queries.

Did you take a look at the code? It also has a code generator and it seems to be pretty useable.
Maybe those projects can be merged and sapper can benefit from it?

**Comment by miketang84** [comment]
emem, in fact, sapper can use any rust orm. Later i will give an example using diesel.  :)

**Comment by Anachron** [comment]
That's great! @daogangtang 

Do you have any reason why you work on a separate ORM instead of helping diesel? :)

**Comment by miketang84** [comment]
in fact, sporm comes from rustorm (at some commit), i update it to latest dependencies.  i used rustorm before, so ....

and i didn't use diesel in any project before, i found that it is not so easy as it said.

**Comment by miketang84** [comment]
hi, sapper_examples has added a diesel crud example, enjoy!

**Comment by miketang84** [comment]
https://github.com/sappworks/sapper_examples/tree/master/mvc_diesel_example

**Comment by Anachron** [comment]
Great, thank you! That was very fast.
