### ISSUE TITLE
Build failed.

### ISSUE THREAD

**Issue by sablib** [daogangtang/sapp-rs#9]
[hyper#67436](https://github.com/hyperium/hyper/commit/67436c5bf615cf5a55a71e32b788afef5985570e)

https://github.com/hyperium/hyper/commit/67436c5bf615cf5a55a71e32b788afef5985570e#diff-e3386610f32c404d2944bf396a387ba4R48
Request 多了泛型参数。

**Comment by miketang84** [comment]
wo qu.

**Comment by miketang84** [comment]
fixed.
